import express from 'express';
const router= express.Router();
import Workout from '../models/workoutModel.js';
import {createWorkout, getWorkouts, getWorkout, deleteWorkout, updateWorkout} from '../controllers/workoutController.js';
router.get("/", getWorkouts);
router.get("/:id", getWorkout);
router.post("/", createWorkout);
router.delete("/:id", deleteWorkout);
router.patch("/:id", updateWorkout);
export default router;